export const ADD_INGREDIRNTS = "ADD_INGREDIRNTS";
export const REMOVE_INGREDIRNTS = "REMOVE_INGREDIRNTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const SET_HOME_MAIN_MENU = "SET_HOME_MAIN_MENU";
export const GET_SUBMENUES = "GET_SUBMENUES";
export const SET_SUBMENUES = "SET_SUBMENUES";
export const GET_SUBMENUES_CONTENT = "GET_SUBMENUES_CONTENT";

export const GET_MENUES = "GET_MENUES";

export const GET_SUBMENUES_FAILED = "GET_SUBMENUES_FAILED";

export const ADD_CONTENT = "ADD_CONTENT";
export const GET_CONTENT_FAILED = "GET_CONTENT_FAILED";

export const UPLOADFILE_START = "UPLOADFILE_START";
export const UPLOADFILE = "UPLOADFILE";
export const UPLOADFILE_FAIL = "UPLOADFILE_FAIL";
export const LOAD_FILE_SUCCESS = "LOAD_FILE_SUCCESS";

export const LOADUSERDETAILS = "LOADUSERDETAILS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_COMPLETE = "UPDATE_USER_COMPLETE";


export const UPDATE_PASSWORD_COMPLETE = "UPDATE_PASSWORD_COMPLETE";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";

export const UPDATE_MAINMENU_SUCCESS = "UPDATE_MAINMENU_SUCCESS";

export const UPDATE_SUBMENU_SUCCESS = "UPDATE_SUBMENU_SUCCESS";

export const DELETE_MAINMENU_SUCCESS = "DELETE_MAINMENU_SUCCESS";

export const DELETE_SUBMENU_SUCCESS = "DELETE_SUBMENU_SUCCESS";
